name: Telegram Bot 机器人脚本

on:
  push:
    branches: [ "main" ] # 或你想要触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果你有 requirements.txt 文件

      - name: Configure Environment Variables
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV # 从 GitHub Secrets 中读取
          echo "OTHER_VARIABLE=${{ vars.OTHER_VARIABLE }}" >> $GITHUB_ENV # 从 GitHub Variables 中读取
          #  你也可以使用手动触发工作流时传入的变量：
          echo "MANUAL_VARIABLE=${{ github.event.inputs.manual_variable }}" >> $GITHUB_ENV

      - name: Run Telegram Bot
        run: |
          python your_bot_script.py  # 替换为你的机器人脚本文件名
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} #  冗余定义，但更清晰
          OTHER_VARIABLE: ${{ vars.OTHER_VARIABLE }} # 冗余定义，但更清晰

