name: Deploy Telegram Bot (Manual Trigger)

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 或者你使用的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run Telegram Bot in Background
        run: |
          nohup python main.py > bot.log 2>&1 &
          echo "Telegram bot started in background. Check bot.log for output."

        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
