name: Telegram Bot

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 0 * * *' # 每天 UTC+0 00:00 运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python your_bot_script.py # 替换为您的脚本文件名
