name: Deploy Telegram Bot (Direct Run)

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 或者你使用的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy to Server (SSH)
        uses: appleboy/ssh-action@master  # 使用 @master 指向最新版本
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/bot/directory  # 替换为你的机器人目录
            git pull origin main  # 拉取最新的代码
            nohup python main.py > bot.log 2>&1 &  # 在后台运行机器人
            echo "Telegram bot started in background. Check bot.log for output."
